### ISSUE TITLE
Support string type for vpc setting in serverless.ts

### ISSUE THREAD

**Issue by shobhit-kb** [serverless/typescript#50] opened 2021-08-23 13:10 UTC
We have use case where we need to apply vpc setting based on stage value. In dev we do not have any vpc setting but for prod and other test env we need one. 

In vpc we want to provide reference to serverless custom fields based on stage
like this
 
```
    memorySize: 512,
    timeout: 300,
    vpc: '${self:custom.vpcSetting.${self:provider.stage}}'

```

but the @serverless/typescript allows vpc to be only of type AwsLambdaVpcConfig 

Please add string type for vpc setting in serverless.ts or provide any other workaround.

**Comment by fredericbarthelet** [comment] 2021-10-14 07:57
Hi @shobhit-kb and thanks for raising this issue.
This actually extends to all serverless variables in any template and is a duplicate of https://github.com/serverless/typescript/issues/11. Feel free to contribute on this issue. Closing this in the meantime.
Thanks :)

**Closed by fredericbarthelet** 2021-10-14 07:57 UTC
Labels: duplicate
