### ISSUE TITLE
Deployment fails with " 'app' does not exist in type 'AWS' "

### ISSUE THREAD

**Issue by vnshgrg** [serverless/typescript#36] opened 2021-03-16 00:52 UTC
I have set up a CI/CD pipeline for my serverless app I was also able to deploy via the pipeline before, but since few days the deployment is failing with the following error. I haven't made any significant changes to my `serverless.ts` file.

```
Cannot load "serverless.ts": Initialization error: TSError: ⨯ Unable to compile TypeScript:
  serverless.ts(19,5): error TS2322: Type '{ app: string; org: string; service: string; frameworkVersion: string; custom: { webpack: { webpackConfig: string; includeModules: boolean; }; customDomain: { domainName: string; basePath: string; stage: string; createRoute53Record: boolean; }; }; plugins: string[]; provider: { ...; }; functions: { ...; }; }' is not assignable to type 'AWS'.
    Object literal may only specify known properties, and 'app' does not exist in type 'AWS'.
```

Is anyone else having similar issues?

**Comment by vnshgrg** [comment] 2021-03-16 01:30
However, when I remove `app` and `org` property from my `serverless.ts` then it seem to work as expected.

```
const serverlessConfiguration: AWS = {
    // app: "...",
    // org: "...",
    ...
}
```

Is this expected behavior?

**Comment by fredericbarthelet** [comment] 2021-03-16 08:20
Hi @vnshgrg and thi and for reporting your issue.

This is a duplicate of #32. app and org properties will be available on next release of serverless/typescript

As for your problem regarding serverless-offline, can you share additional information regarding the issue ?

**Comment by vnshgrg** [comment] 2021-03-16 15:15
Hello @fredericbarthelet 
Oh, for the `serverless-offline` plugin commenting out `app` and `org` fails the offline plugin as it is unable to figure out where to look for params stored in serverless dashboard.

for now changed this:
```
const serverlessConfiguration: AWS = {
```
to this:
```
const serverlessConfiguration: AWS & { app?: string; org?: string } = {
```

seem to work for me for both deployment and local development.

**Comment by fredericbarthelet** [comment] 2021-03-18 08:13
Hi @vnshgrg, `v2.30.3` of this package, just released, now defines `app` and `org` parameter in `AWS` type :)

https://github.com/serverless/typescript/blob/a4afa81d5a223f635a7dd8498fabc630ec368401/index.d.ts#L1284-L1285

Feel free to update your local package version. I'm closing this, feel free to re-open in case you face the same issue again.

**Closed by fredericbarthelet** 2021-03-18 08:13 UTC
Labels: duplicate
